_target_: sfols.rl.successor_features.tabular_sf.SF
alpha: 0.3
gamma: 0.99
initial_epsilon: 1
final_epsilon: 0.1
epsilon_decay_steps: 5000
learning_starts: 2000
use_replay: True
per: False
use_gpi: True
envelope: False
batch_size: 10
buffer_size: 5000
log: True
